## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [3]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos_mat'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos_por'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos_geo'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos_ing'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos_his'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos_fis'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos_qui'])

tabela_geral = pd.df = pd.concat([df_mat, df_por, df_geo, df_ing, df_his, df_fis, df_qui], axis=1)
tabela_geral

,Qt_acertos_mat,Qt_acertos_por,Qt_acertos_geo,Qt_acertos_ing,Qt_acertos_his,Qt_acertos_fis,Qt_acertos_qui
0,6,7,7,3,1,8,3
1,19,10,0,0,0,11,8
2,14,16,0,5,7,4,4
3,10,7,3,4,0,0,8
4,7,2,2,7,0,9,3
...,...,...,...,...,...,...,...
95,6,4,7,1,4,9,3
96,8,1,4,6,1,4,3
97,23,5,0,2,4,1,5
98,0,10,3,1,5,10,11
99,11,15,0,1,6,7,2

In [4]:
# 1) Seu código aqui

porc_acertos_mat = df_mat/24

porc_acertos_por = df_por/18

porc_acertos_ing = df_ing/8

porc_acertos_his = df_his/8

porc_acertos_fis = df_fis/12

porc_acertos_qui = df_qui/12

In [5]:
# 2) Seu código aqui
tabela_geral ["acertos_totais"] = (tabela_geral['Qt_acertos_fis'] + tabela_geral['Qt_acertos_geo'] + 
                                   tabela_geral['Qt_acertos_his'] + tabela_geral['Qt_acertos_ing'] + 
                                   tabela_geral['Qt_acertos_mat'] + tabela_geral['Qt_acertos_por'] +
                                   tabela_geral['Qt_acertos_qui'] )
tabela_geral

,Qt_acertos_mat,Qt_acertos_por,Qt_acertos_geo,Qt_acertos_ing,Qt_acertos_his,Qt_acertos_fis,Qt_acertos_qui,acertos_totais
0,6,7,7,3,1,8,3,35
1,19,10,0,0,0,11,8,48
2,14,16,0,5,7,4,4,50
3,10,7,3,4,0,0,8,32
4,7,2,2,7,0,9,3,30
...,...,...,...,...,...,...,...,...
95,6,4,7,1,4,9,3,34
96,8,1,4,6,1,4,3,27
97,23,5,0,2,4,1,5,40
98,0,10,3,1,5,10,11,40
99,11,15,0,1,6,7,2,42

In [6]:
# 3) Seu código aqui
porc_total_acertos= tabela_geral['acertos_totais']/90
porc_total_acertos

0     0.388889
1     0.533333
2     0.555556
3     0.355556
4     0.333333
        ...
95    0.377778
96    0.300000
97    0.444444
98    0.444444
99    0.466667
Name: acertos_totais, Length: 100, dtype: float64

In [7]:
# 4) Seu código aqui
alunos_acertos_maior_45 = tabela_geral.loc[tabela_geral['acertos_totais'] >45, 'acertos_totais']
alunos_acertos_maior_45.count()

31

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [8]:
# seu código aqui
#1)
# seu código aqui 
df_desq = tabela_geral[(['Qt_acertos_mat'] == 0) | 
                      (tabela_geral['Qt_acertos_fis'] == 0) | 
                      (tabela_geral['Qt_acertos_qui'] == 0)]

df_desq

,Qt_acertos_mat,Qt_acertos_por,Qt_acertos_geo,Qt_acertos_ing,Qt_acertos_his,Qt_acertos_fis,Qt_acertos_qui,acertos_totais
3,10,7,3,4,0,0,8,32
6,6,0,7,7,5,0,4,29
10,10,8,3,2,1,7,0,31
12,20,8,3,7,1,0,3,42
14,7,11,1,7,1,4,0,31
20,23,11,6,5,6,2,0,53
26,11,14,6,2,7,0,0,40
27,21,13,1,5,7,3,0,50
33,14,8,0,5,6,6,0,39
35,11,14,6,3,3,0,11,48
49,8,1,1,0,1,0,8,19
56,7,6,7,5,6,0,8,39
65,1,8,2,4,3,0,6,24
66,5,4,3,6,3,0,10,31
72,11,16,3,4,7,0,9,50
73,1,16,2,4,3,0,11,37
74,9,11,0,7,5,7,0,39
84,15,1,0,5,1,0,4,26
89,23,11,7,7,6,9,0,63
92,14,10,1,6,1,8,0,40

In [9]:
#2)
df_desq.count()

Qt_acertos_mat    20
Qt_acertos_por    20
Qt_acertos_geo    20
Qt_acertos_ing    20
Qt_acertos_his    20
Qt_acertos_fis    20
Qt_acertos_qui    20
acertos_totais    20
dtype: int64

In [10]:
#3) Média em História
desq_med_his = df_desq["Qt_acertos_his"].mean()
desq_med_his

3.65

In [11]:
#3) Média em Geografia
desq_med_geo = df_desq["Qt_acertos_geo"].mean()
desq_med_geo

3.1

In [14]:
#4
alunos_passaram = tabela_geral.drop(index=df_desq.index) 
alunos_passaram

,Qt_acertos_mat,Qt_acertos_por,Qt_acertos_geo,Qt_acertos_ing,Qt_acertos_his,Qt_acertos_fis,Qt_acertos_qui,acertos_totais
0,6,7,7,3,1,8,3,35
1,19,10,0,0,0,11,8,48
2,14,16,0,5,7,4,4,50
4,7,2,2,7,0,9,3,30
5,20,2,5,3,2,9,9,50
...,...,...,...,...,...,...,...,...
95,6,4,7,1,4,9,3,34
96,8,1,4,6,1,4,3,27
97,23,5,0,2,4,1,5,40
98,0,10,3,1,5,10,11,40
99,11,15,0,1,6,7,2,42

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [29]:
arquivo = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-97829158-cc41-4c75-aec4-752344e6e938.c000.csv'

In [33]:

df = pd.read_csv(arquivo, sep=';')
df.head(8)

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,a7b2e803-75ae-4c59-baa7-421d87f9a707-i0b0,3e35925a3512d7901cd2974eb662e25b6130ee42e72317...,30,1991-08-30,F,4,AMARELA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,205F21A,JANSSEN,Organization/30587,2022-05-26,Reforço,88,COVID-19 JANSSEN - Ad26.COV2.S,Novo PNI
1,5ec41855-c5b8-44de-88d0-a474814e9df0-i0b0,ac91ba1d57f1ec0a8c88e393ed7e162914cecaa47d8624...,38,1982-09-20,F,2,PRETA,120020.0,10.0,CRUZEIRO DO SUL,...,2.0,Faixa Etária,214VCD053W,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-07-02,1ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
2,c5b89122-8166-4f7e-9ef3-1a98c8e65d52-i0b0,578eff022445b36a42ef61a011ec5517523a563c5321a7...,20,2001-03-21,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/00394544000851,2021-10-25,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
3,5ef90995-413a-44df-bfb2-64dec20fc20f-i0b0,6991fbfb4e56ef4193b09f7a6203604356b3c3b739101e...,30,1990-12-07,M,4,AMARELA,120050.0,10.0,SENA MADUREIRA,...,2.0,Faixa Etária,214VCD053W,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-08-03,2ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
4,7177c695-3e14-42fd-8a7c-ef76ebe92360-i0b0,b1ead8d542ffb8e8f387426cb6e134d39979759c1ae190...,63,1957-06-09,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,210135,SINOVAC/BUTANTAN,Organization/61189445000156,2021-05-10,2ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
5,5ef9c979-cd95-4a7e-b4ca-40eddba05af3-i0b0,488a76d5c8ffe25c04ed138416441e0767c2cbe607d9be...,34,1987-05-22,M,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,6.0,Povos e Comunidades Tradicionais,217VCD227Z,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-09-07,2ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
6,74629aec-ea92-40cd-868e-23620e6cd055-i0b0,23545e868e3c4555ca5b0452613d44275102e44d432e27...,15,2006-01-15,M,99,SEM INFORMACAO,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/00394544000851,2021-10-09,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
7,5f075166-5ef1-42be-bee5-f1d1d72f9d56-i0b0,bc431684cb4e15c80239cf664bb9d75a68b5ea3083d2d9...,74,1948-10-23,M,1,BRANCA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,GF9670,PFIZER,28290,2023-03-02,Reforço,103,COVID-19 PFIZER - COMIRNATY BIVALENTE,Novo PNI

In [39]:
# 1) Sua solução aqui
df.vacina_nome.nunique()

12

In [38]:
# 2)
df.paciente_id.nunique()

308842

In [49]:
# 3) 
df_1a_dose= df.loc[df['vacina_descricao_dose']=='1ª Dose']
df_1a_dose.paciente_id.nunique()

141243

In [50]:
# 4)
df_menor_18 = df.loc[df['paciente_idade']<18]
df_menor_18.paciente_id.nunique()

63276

In [58]:
df['estabelecimento_razaoSocial']

0                   SECRETARIA MUNICIPAL DE SAUDE
1                   PREFEITURA MUNICIPAL DE SAUDE
2              PREFEITURA MUNICIPAL DE RIO BRANCO
3         PREFEITURA MUNICIIPAL DE SENA MADUREIRA
4              PREFEITURA MUNICIPAL DE RIO BRANCO
                           ...
375519     PREFEITURA MUNICIPAL DE SENA MADUREIRA
375520         PREFEITURA MUNICIPAL DE RIO BRANCO
375521     PREFEITURA MUNICIPAL DE SENA MADUREIRA
375522    PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL
375523         PREFEITURA MUNICIPAL DE RIO BRANCO
Name: estabelecimento_razaoSocial, Length: 375524, dtype: object

In [57]:
# 5)
df.estabelecimento_razaoSocial.nunique()

55

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [64]:
# 1)
df_menor_18 = df[df["paciente_idade"]<18].copy()
df_menor_18

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
6,74629aec-ea92-40cd-868e-23620e6cd055-i0b0,23545e868e3c4555ca5b0452613d44275102e44d432e27...,15,2006-01-15,M,99,SEM INFORMACAO,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/00394544000851,2021-10-09,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
9,5f2afecd-7550-4f5c-9afb-86043a6f06aa-i0b0,3c801e3d6595fb034082a1477d767e3e8a6a5a8830a964...,12,2009-08-27,M,3,PARDA,120005.0,10.0,ASSIS BRASIL,...,2.0,Faixa Etária,31065BD,PFIZER,Organization/28290,2022-01-10,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
14,96b08b97-3224-4c9c-aec7-9c03fbddb3cc-i0b0,3e955dff89eac98b6f8c9bf109305e0bea141ca33acacd...,15,2006-10-15,F,3,PARDA,130260.0,10.0,MANAUS,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/28290,2022-03-03,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
18,e5c2279b-611f-43d3-90f7-464bf7b922ed-i0b0,c189e5cc642304dacfa601cb29e7be6b704b6d9355397f...,16,2005-08-16,F,4,AMARELA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/00394544000851,2021-10-11,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
24,8d55063b-1d12-4a97-8351-c1263f110e81-i0b0,563a39a555f59fe2e01a974c7f619d069f6d2316eef22a...,7,2014-11-19,M,5,INDIGENA,120043.0,10.0,SANTA ROSA DO PURUS,...,NaN,NaN,FP8290,Pendente Identificação,Organization/28290,2022-02-24,1ª Dose,99,COVID-19 PEDIÁTRICA - PFIZER COMIRNATY,Novo PNI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375504,cf5b652c-f907-41d1-85db-26594905599f-i0b0,2c07abbe2e0affb7b5dfb01bd16ccf7ede1d26c0197cc1...,13,2007-10-20,F,1,BRANCA,120020.0,10.0,CRUZEIRO DO SUL,...,114.0,Outros,FA9096,PFIZER,Organization/00394544000851,2021-07-31,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
375505,cfc17e79-db4f-46e6-9984-3e9245b77d35-i0b0,cac90ce49536034dcaf054c9bc9b5e3ad897086fd0e18e...,13,2008-03-18,M,3,PARDA,120035.0,10.0,MARECHAL THAUMATURGO,...,9.0,Trabalhadores de Saúde,ED7207,PFIZER,NaN,2021-11-29,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,ESUS APS - NACIONAL (OFFLINE)
375518,d0dbece5-33d7-4e29-982c-aa26bea10ac1-i0b0,5a151565aa08f0edcd01f22fb8e5c548cf0cfe9561efd3...,12,2008-09-29,F,3,PARDA,120020.0,10.0,CRUZEIRO DO SUL,...,2.0,Faixa Etária,FA9096,PFIZER,Organization/00394544000851,2021-08-09,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
375521,d1512879-1dcd-4a80-9dca-21597ac68b9b-i0b0,99c9f90fc09e314b4f3dbbf6ecfccc666d5c00c8c2c01c...,17,2004-05-07,M,4,AMARELA,120050.0,10.0,SENA MADUREIRA,...,2.0,Faixa Etária,FA9096,PFIZER,Organization/00394544000851,2021-08-11,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
375522,d15e007a-f7d9-43f2-bb5c-94a0986f4cf7-i0b0,00a2cf8cb156ba7c3b61116431c4f1a0a5b175233a872a...,11,2010-08-09,F,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,NaN,NaN,FN4073,PFIZER - PEDI?TRICA,28290,2022-07-29,1ª Dose,99,COVID-19 PEDIÁTRICA - PFIZER COMIRNATY,Novo PNI

In [54]:
# 2)
df_menor_18.columns

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_dataNascimento', 'paciente_enumSexoBiologico',
       'paciente_racaCor_codigo', 'paciente_racaCor_valor',
       'paciente_endereco_coIbgeMunicipio', 'paciente_endereco_coPais',
       'paciente_endereco_nmMunicipio', 'paciente_endereco_nmPais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumNacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoAtendimento_codigo',
       'vacina_grupoAtendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataAplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem'],
      dtype='object')

In [65]:
# 3)
df_menor_18.vacina_categoria_nome.value_counts()

vacina_categoria_nome
Faixa Etária                                      42455
Povos Indígenas                                    3829
Outros                                             3697
Povos e Comunidades Tradicionais                    681
Trabalhadores de Saúde                              238
Comorbidades                                         55
População Privada de Liberdade                       51
Gestantes                                            34
Pessoas com Deficiência                              10
Pessoas Institucionalizadas                           3
Pessoas de 60 anos ou mais institucionalizadas        1
Puérperas                                             1
Trabalhadores da Educação                             1
Name: count, dtype: int64

In [72]:
# 4)
df_menor_18_lista_estab = df_menor_18.loc[:,'estabelecimento_valor':'estabelecimento_uf']
df_menor_18_lista_estab

,estabelecimento_valor,estabelecimento_razaoSocial,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
6,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
9,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC
14,2000156,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE BASICA DE SAUDE JOAO WANDERLEI,120060,TARAUACA,AC
18,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
24,2001772,PREFEITURA MUNICIPAL DE SANTA ROSA DO PURUS,CENTRO DE SAUDE PAULO ALCIONE MARQUES,120043,SANTA ROSA DO PURUS,AC
...,...,...,...,...,...,...
375504,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
375505,2002132,PREFEITURA MUN DE MAL THAUMATURGO,ESF RIBEIRINHA DR NALDIR MARIANO,120035,MARECHAL THAUMATURGO,AC
375518,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
375521,2002566,PREFEITURA MUNICIPAL DE SENA MADUREIRA,UNIDADE BASICA DE SAUDE LAURO FONTES DA SILVA,120050,SENA MADUREIRA,AC
375522,2000326,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE DE SAUDE DA FAMILIA GEOSETE COELHO MAR...,120020,CRUZEIRO DO SUL,AC

In [74]:
# 5)
df_menor_18_lista_estab = df_menor_18_lista_estab.drop_duplicates()
df_menor_18_lista_estab.shape

(178, 6)